### ISSUE TITLE
[REQ] Fix license file

### ISSUE THREAD

**Issue by MarcoRavich** [antimodular/ofxVisca#2]
Hi there, 1st of all thanks for this cool work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [VIDEO category](https://github.com/forart/HyMPS#-1) \ [Pan Tilt Zoom page](https://github.com/forart/HyMPS/blob/main/V_PTZ.md#--) \ [VISCA subsection](https://github.com/forart/HyMPS/blob/main/V_PTZ.md#visca-)), can you please fix the license for it ?

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/antimodular/ofxVisca/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/antimodular/ofxVisca/?label=LICENSE)

Anyway you can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by MarcoRavich** [comment]
Bump (request updated).

**Comment by stephanschulz** [comment]
we do have a License:
https://github.com/antimodular/ofxVisca?tab=License-1-ov-file

**Comment by MarcoRavich** [comment]
> we do have a License: https://github.com/antimodular/ofxVisca?tab=License-1-ov-file
>
1st of all, thanks for the quick reply.

I had already checked your license file of course (hence the fix request), but it seems that it isn't "recognized" by GH...
...to get an idea, check out this one - which is instead - from another project (ptzbot): 
https://github.com/wcameronbowen/ptzbot?tab=MIT-1-ov-file

Thanks in advance.

EDIT: it could also be a mere formatting problem... maybe the badge below?

**Comment by stephanschulz** [comment]
I removed the image link. see if that makes it any better.
[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)

**Comment by MarcoRavich** [comment]
Yup, as you can see, it works now.

Thanks !
